#!/bin/bash
#PBS -N lvcsh
#PBS -o ${PBS_JOBID}.out
#PBS -e ${PBS_JOBID}.err
#PBS -q share
#PBS -l nodes=1:ppn=28

# get the number of processors
NP=`cat $PBS_NODEFILE | wc -l`

# enter job's working directory
cd $PBS_O_WORKDIR

#export OMP_NUM_THREADS=1
#export MKL_NUM_THREADS=1
export MODULEPATH=/public/software/modules:/public/home/wzhuang/xh/modulefiles

module load apps/MD/LVCSH/0.1.0

for i in {1..56}
do
mkdir sample$i
cp ./LVCSH.in ./sample$i/
cd ./sample$i
LVCSH.x &
cd ..
done
wait


